#!/bin/bash

mkdir -p out

for input in "scale-out" "scale-up" "security" "storage"; do
  echo "... processing $input.tex"
  docker run --rm \
    --workdir='/root/' \
    -v `pwd`/:/mnt \
    -v `pwd`/$input.tex:/root/$input.tex \
    -v `pwd`/references.bib:/root/references.bib \
    -v `pwd`/out:/root/out \
    ivotron/texlive:latest sh -c \
      "pdflatex $input
       bibtex $input &&
       pdflatex $input &&
       pdflatex $input &&
       mv $input.pdf /root/out/" &> build.log
  
  if [ $? != "0" ] ; then
    echo "ERROR"
    cat build.log
    rm build.log
    exit 1
  fi
  
  mv out/$input.pdf .
  rm -r out
  rm build.log
done

exit 0
