#!/bin/bash
set -x
mkdir -p out

cp biblio/references.bib references.bib

docker run --rm \
  --workdir='/root/' \
  -v `pwd`/paper.tex:/root/paper.tex \
  -v `pwd`/references.bib:/root/references.bib \
  -v `pwd`/sections:/root/sections \
  -v `pwd`/figures:/root/figures \
  -v `pwd`/.deps/acmart.cls:/root/acmart.cls \
  -v `pwd`/.deps/ACM-Reference-Format.bst:/root/ACM-Reference-Format.bst \
  -v `pwd`/out:/root/out \
  --entrypoint=/bin/bash \
  michaelsevilla/texlive:latest -c \
    "pdflatex -shell-escape paper;
     bibtex paper;
     pdflatex -shell-escape paper;
     pdflatex -shell-escape paper;
     mv paper.pdf /root/out/" &> build.log
  #--entrypoint=/bin/bash -it michaelsevilla/texlive:latest
    
  #tianon/latex sh -c \

if [ $? != "0" ] ; then
  echo "ERROR"
  cat build.log
  rm build.log
  exit 1
fi

mv out/paper.pdf .
rm -r out
rm build.log

exit 0
